serial:
   port: "/dev/ttyACM0"
   debug: False
   interval: 5

mqtt:
   host: "192.168.0.10"
   port: 1883 
   device_id: "ragtech_ups"
   #user: "foo"      #(optional)
   #password: "bar"  #(optional)